### ISSUE TITLE
Installing on FreeBSD 10.1 fails with "cannot find -lstdc++"

### ISSUE THREAD

**Issue by cubranic** [garaio/xapian-ruby#3]
```
/bin/sh ../libtool  --tag=CXX    --mode=link c++ -fno-strict-aliasing -Wall -Wno-unused -Wno-uninitialized -fvisibility=hidden -I/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/include  -g -O2 -avoid-version -module -shrext ".so"  -L/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/lib -o _xapian.la -rpath /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/site_ruby/2.0.0/x86_64-freebsd10.1 xapian_wrap.lo /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/libxapian.la -lstdc++  
libtool: link: c++  -fPIC -DPIC -shared -nostdlib /usr/lib/crti.o /usr/lib/crtbeginS.o  .libs/xapian_wrap.o   -Wl,-rpath -Wl,/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/.libs -Wl,-rpath -Wl,/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/lib -L/usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/lib /usr/home/davor/.rbenv/versions/2.0.0-p645/lib/ruby/gems/2.0.0/gems/xapian-ruby-1.2.20/xapian-core-1.2.20/.libs/libxapian.so -lz -lstdc++ -L/usr/lib -lc++ -lm -lc -lgcc -lgcc_s /usr/lib/crtendS.o /usr/lib/crtn.o  -O2   -Wl,-soname -Wl,_xapian.so -o .libs/_xapian.so
/usr/bin/ld: cannot find -lstdc++
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by gernotkogler** [comment]
xapian-ruby ist basically a wrapper around the xapian source + makefiles. If it doesn't install on your environment there are probably missing dependencies or your environment ist not supported by xapian.

**Comment by cubranic** [comment]
There are no issues about dependencies, but xapian-bindings' `configure` for some reason ends up with a hard-coded `-lstdc++`, which is a GNU-only library and not present on the current release FreeBSD by default. You can see this in FreeBSD's port of xapian-bindings, which removes this switch from the generated `configure` prior to running it: http://svnweb.freebsd.org/ports/head/databases/xapian-bindings/Makefile?revision=HEAD&view=markup#l44 

I agree that there isn't much you can do, it's something that Xapian should fix. (Or maybe GNU, I'm not sure why it doesn't recognize that the compiler used is clang and not g++.) In the meantime, it's easy enough for me to edit the source left in the gem's directory and finish the installation by hand.
